name: ci pipeline

on:
  push:
    branches:
      - master
      - feature/**

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  docker:
    name: docker
    runs-on: ubuntu-latest
    env:
      GIT-SHA-TAG: git rev-parse --short ${{ github.sha }}
    steps:
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: docker build
        uses: docker/setup-buildx-aaction@v3

      -
        name: set git-sha-short tag
        run: echo "GIT-SHA-TAG = $git rev-parse --short ${{ github.sha }}" >> $GITHUB_ENV

      -
        name: docker build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeoff-manegement:$GIT-SHA-TAG


  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: print building
        run:
          echo Building this image
      - name: building the image
        run:
          docker build -t timeoffmanagement:latest .
      - name: print built
        run:
          echo Image built

# i need to put env credentials
  upload:
    name: upload
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print pushing
        run:
          echo pushing to dockerhuub
      - name: push to dockerhub
      - name: docker login
          run:
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ DOCKERHUB_PASSWORD }}
        run:
          docker tag abdullahawad00/timeoffmanagement:latest
      - name: print uploaded
        run:
          docker push abdullahawad00/timeoffmanagement:latest
